aws:
  region: ap-southeast-2
  s3:
    bucket: amzn-s3-unicode
spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  end-point: https://test-payment.momo.vn/v2/gateway/api
  return-url: http://localhost:8080/api/v1/subscriptions/momo/call-back
  request-type: payWithMethod
cloudinary:
   cloud_name: duswlfkbc
   api_key: 927358387459548
   api_secret: AJbJFhnLJE33i0qhLwWMCXhUc8E





